# -*- coding: utf-8 -*-
"""cs180_proj5b_release.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqpAzvLuPwYiwJaY0xLEqdx5IkBNqk1B

# Project 5B: Flow Matching from Scratch!

## Setup environment
"""

# We recommend using these utils.
# https://google.github.io/mediapy/mediapy.html
# https://einops.rocks/
!pip install mediapy einops --quiet

# Import essential modules. Feel free to add whatever you need.
import torch
import mediapy as media
import matplotlib.pyplot as plt
from torch import nn
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
from torchvision.utils import make_grid
from tqdm import tqdm


import matplotlib.pyplot as plt
from torch import nn
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
from tqdm import tqdm

"""## Neural Network Resources

In this part, you will build and train a [UNet](https://arxiv.org/abs/1505.04597), which is more complex than the MLP you implemented in the NeRF project.  We provide all class definitions you may need (but feel free to add or modify them as necessary).  

Instead of asking ChatGPT to write everything for you, please consult the following resources when you get stuck — they will help you understand how and why things work under the hood.

- PyTorch Documentation — [`Conv2d`](https://docs.pytorch.org/docs/stable/generated/torch.nn.Conv2d.html), [`ConvTranspose2d`](https://docs.pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html), and [`AvgPool2d`](https://docs.pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html).
- PyTorch Documentation - [`torchvision.datasets.MNIST`](https://docs.pytorch.org/vision/main/generated/torchvision.datasets.MNIST.html), the dataset we gonna use, and [`torch.utils.data.DataLoader`](https://docs.pytorch.org/docs/stable/data.html), the off-the-shell dataloader we can directly use.
- PyTorch [tutorial](https://docs.pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html) on how to train a classifier on CIFAR10 dataset. The structure of your training code will be very similar to this one.

# Part 1: Training a Single-step Denoising UNet

# Part 1.1: Implementing the UNet

## Implementing Simple and Composed Ops
"""

class Conv(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        # ===== your code here! ====
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=1, padding=1)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = nn.GELU()
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        x = self.conv(x)
        x = self.bn(x)
        x = self.act(x)
        return x
        # ===== end of code ====


class DownConv(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        # ===== your code here! ====
        # Downsample by factor 2
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=4, stride=2, padding=1)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = nn.GELU()
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        x = self.conv(x)
        x = self.bn(x)
        x = self.act(x)
        return x
        # ===== end of code ====


class UpConv(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        # ===== your code here! ====
        # Upsample by factor 2
        self.conv = nn.ConvTranspose2d(in_channels, out_channels, kernel_size=4, stride=2, padding=1)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = nn.GELU()
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        x = self.conv(x)
        x = self.bn(x)
        x = self.act(x)
        return x
        # ===== end of code ====


class Flatten(nn.Module):
    def __init__(self):
        super().__init__()
        # ===== your code here! ====
        # Assume input is (B, C, 7, 7) -> (B, C, 1, 1)
        self.pool = nn.AvgPool2d(kernel_size=7)
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        return self.pool(x)
        # ===== end of code ====


class Unflatten(nn.Module):
    def __init__(self, in_channels: int):
        super().__init__()
        # ===== your code here! ====
        # (B, C, 1, 1) -> (B, C, 7, 7)
        self.conv = nn.ConvTranspose2d(in_channels, in_channels, kernel_size=7, stride=1, padding=0)
        self.bn = nn.BatchNorm2d(in_channels)
        self.act = nn.GELU()
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        x = self.conv(x)
        x = self.bn(x)
        x = self.act(x)
        return x
        # ===== end of code ====


class ConvBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        # ===== your code here! ====
        # Two Conv layers, same spatial size
        self.block = nn.Sequential(
            Conv(in_channels, out_channels),
            Conv(out_channels, out_channels),
        )
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        return self.block(x)
        # ===== end of code ====


class DownBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        # ===== your code here! ====
        # DownConv then Conv to deepen features
        self.block = nn.Sequential(
            DownConv(in_channels, out_channels),
            Conv(out_channels, out_channels),
        )
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        return self.block(x)
        # ===== end of code ====


class UpBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        # ===== your code here! ====
        # UpConv then Conv to refine
        self.block = nn.Sequential(
            UpConv(in_channels, out_channels),
            Conv(out_channels, out_channels),
        )
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        return self.block(x)
        # ===== end of code ====

"""## Implementing Unconditional UNet"""

class UnconditionalUNet(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_hiddens: int,
    ):
        super().__init__()
        # ===== your code here! ====
        D = num_hiddens

        # Encoder
        self.enc1 = ConvBlock(in_channels, D)   # 28x28
        self.enc2 = DownBlock(D, D)            # 14x14
        self.enc3 = DownBlock(D, D)            # 7x7

        # Bottleneck
        self.flatten = Flatten()               # 1x1
        self.mid = ConvBlock(D, D)             # 1x1 conv block
        self.unflatten = Unflatten(D)          # back to 7x7

        # Decoder with skip connections
        self.dec3 = UpBlock(D * 2, D)          # 7x7 -> 14x14
        self.dec2 = UpBlock(D * 2, D)          # 14x14 -> 28x28
        self.out_conv = nn.Conv2d(D * 2, in_channels, kernel_size=3, stride=1, padding=1)
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert x.shape[-2:] == (28, 28), "Expect input shape to be (28, 28)."
        # ===== your code here! ====
        # Encoder
        x1 = self.enc1(x)       # (B, D, 28, 28)
        x2 = self.enc2(x1)      # (B, D, 14, 14)
        x3 = self.enc3(x2)      # (B, D, 7, 7)

        # Bottleneck
        xb = self.flatten(x3)   # (B, D, 1, 1)
        xb = self.mid(xb)       # (B, D, 1, 1)
        xb = self.unflatten(xb) # (B, D, 7, 7)

        # Decoder with skip connections
        d3 = self.dec3(torch.cat([xb, x3], dim=1))  # (B, D, 14, 14)
        d2 = self.dec2(torch.cat([d3, x2], dim=1))  # (B, D, 28, 28)
        out = self.out_conv(torch.cat([d2, x1], dim=1))  # (B, in_ch, 28, 28)
        return out
        # ===== end of code ====

"""# Part 1.2: Using the UNet to Train a Denoiser"""

# Visualize images at different noisy level
# ===== your code here! ====

def add_noise(x: torch.Tensor, sigma: float) -> torch.Tensor:
    """Add Gaussian noise N(0, sigma^2) to images x."""
    return x + sigma * torch.randn_like(x)

# Use MNIST with ToTensor() only (values in [0,1])
vis_dataset = MNIST(root="./data", train=True, download=True, transform=ToTensor())
vis_loader = DataLoader(vis_dataset, batch_size=8, shuffle=True)

images, _ = next(iter(vis_loader))  # (8,1,28,28)
sigmas = [0.0, 0.2, 0.5]

imgs = {}

# Original grid
grid_orig = make_grid(images, nrow=8, padding=2)
imgs["original"] = grid_orig.permute(1, 2, 0).cpu()

for s in sigmas:
    noisy = add_noise(images, s).clamp(0.0, 1.0)
    grid_noisy = make_grid(noisy, nrow=8, padding=2)
    imgs[f"sigma={s}"] = grid_noisy.permute(1, 2, 0).cpu()

media.show_images(imgs)
# ===== end of code ====

"""## Part 1.2.1: Training

For this part, we provide some structure code for training. It is very basic, so feel free to change them or add your code. In later section we won't provide any training or visualization structure code.
"""

device = torch.device('cuda')

# Set your hyperparameters
# ===== your code here! ====
batch_size = 256
learning_rate = 1e-4
noise_level = 0.5    # σ used during training
hidden_dim = 128
num_epochs = 5
# ===== end of code ====

# Define your datasets and dataloaders
# ===== your code here! ====
transform = ToTensor()  # images in [0,1]

train_dataset = MNIST(root="./data", train=True, download=True, transform=transform)
test_dataset  = MNIST(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader  = DataLoader(test_dataset,  batch_size=batch_size, shuffle=False)
# ===== end of code ====

# Define your model, optimizer, and loss
# ===== your code here! ====
model = UnconditionalUNet(in_channels=1, num_hiddens=hidden_dim).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()
# ===== end of code ====

# The training loops
train_losses = []
for epoch in range(num_epochs):
    for i, (images, _) in enumerate(tqdm(train_loader)):

        # ===== your code here! ====
        images = images.to(device)                      # clean images in [0,1]
        noisy_images = add_noise(images, noise_level)   # add training noise

        outputs = model(noisy_images)                   # predict clean images
        # ===== end of code ====

        loss = criterion(outputs, images)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_losses.append(loss.item())

    print(f"Epoch [{epoch+1}/{num_epochs}] - Loss: {loss.item():.6f}")

# Visualize your training curve
# ===== your code here! ====
plt.figure(figsize=(6,4))
plt.plot(train_losses)
plt.xlabel("Iteration")
plt.ylabel("MSE Loss")
plt.title("Denoiser training loss (σ=0.5)")
plt.grid(True)
plt.show()

# Also visualize denoising on test set after training (σ = 0.5)
model.eval()
with torch.no_grad():
    test_images, _ = next(iter(test_loader))
    test_images = test_images[:8].to(device)
    noisy_test = add_noise(test_images, noise_level)
    denoised = model(noisy_test).clamp(0.0, 1.0)

    imgs = {}
    imgs["clean"] = make_grid(test_images.cpu(), nrow=8, padding=2).permute(1,2,0)
    imgs["noisy_sigma=0.5"] = make_grid(noisy_test.cpu().clamp(0,1), nrow=8, padding=2).permute(1,2,0)
    imgs["denoised"] = make_grid(denoised.cpu(), nrow=8, padding=2).permute(1,2,0)

    media.show_images(imgs)
# ===== end of code ====

"""## Part 1.2.2: Out-of-Distribution Testing"""

# Visualize OOD testing
# ===== your code here! ====

model.eval()
test_images, _ = next(iter(test_loader))
test_images = test_images[:8].to(device)

sigmas_ood = [0.1, 0.3, 0.7, 1.0]

imgs = {}
imgs["clean"] = make_grid(test_images.cpu(), nrow=8, padding=2).permute(1, 2, 0)

with torch.no_grad():
    for s in sigmas_ood:
        noisy = add_noise(test_images, s)
        denoised = model(noisy).clamp(0.0, 1.0)

        grid_noisy = make_grid(noisy.cpu().clamp(0,1), nrow=8, padding=2)
        grid_denoised = make_grid(denoised.cpu(), nrow=8, padding=2)

        imgs[f"noisy_sigma={s}"] = grid_noisy.permute(1,2,0)
        imgs[f"denoised_sigma={s}"] = grid_denoised.permute(1,2,0)

media.show_images(imgs)
# ===== end of code ====

"""## Part 1.2.3 Denoising Pure Noise"""

# Feel free to use code from part 1.2.1
# as they should be very similar
# ===== your code here! ====

pure_model = UnconditionalUNet(in_channels=1, num_hiddens=hidden_dim).to(device)
pure_optimizer = torch.optim.Adam(pure_model.parameters(), lr=learning_rate)
pure_criterion = nn.MSELoss()

pure_train_losses = []

for epoch in range(num_epochs):
    for i, (images, _) in enumerate(tqdm(train_loader)):
        images = images.to(device)                  # clean digits in [0,1]
        noise_input = torch.randn_like(images)      # pure noise input

        outputs = pure_model(noise_input)           # try to map noise -> digit
        loss = pure_criterion(outputs, images)

        pure_optimizer.zero_grad()
        loss.backward()
        pure_optimizer.step()

        pure_train_losses.append(loss.item())

    print(f"[Pure noise model] Epoch [{epoch+1}/{num_epochs}] - Loss: {loss.item():.6f}")

# Loss curve
plt.figure(figsize=(6,4))
plt.plot(pure_train_losses)
plt.xlabel("Iteration")
plt.ylabel("MSE Loss")
plt.title("Pure-noise denoiser training loss")
plt.grid(True)
plt.show()

# Visualize outputs on pure noise after 1st and 5th epoch equivalent
# (Here we just show after final training; you can also log at epoch 1 manually)
pure_model.eval()
with torch.no_grad():
    z = torch.randn(8, 1, 28, 28, device=device)   # pure noise
    outputs = pure_model(z).clamp(0.0, 1.0)

    imgs = {}
    imgs["input_noise"] = make_grid(z.cpu().clamp(0,1), nrow=8, padding=2).permute(1,2,0)
    imgs["output"]      = make_grid(outputs.cpu(), nrow=8, padding=2).permute(1,2,0)

    media.show_images(imgs)
# ===== end of code ====

"""# Part 2: Flow Matching

# Part 2.1: Implementing a Time-conditioned UNet
"""

class FCBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()
        # ===== your code here! ====
        self.net = nn.Sequential(
            nn.Linear(in_channels, out_channels),
            nn.GELU(),
            nn.Linear(out_channels, out_channels),
            nn.GELU(),
        )
        # ===== end of code ====

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # ===== your code here! ====
        return self.net(x)
        # ===== end of code ====
        raise NotImplementedError()


class TimeConditionalUNet(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        num_hiddens: int,
    ):
        super().__init__()
        # ===== your code here! ====
        self.in_channels = in_channels
        self.num_hiddens = num_hiddens

        D = num_hiddens

        # Encoder
        self.enc1 = ConvBlock(in_channels, D)   # 28x28
        self.enc2 = DownBlock(D, D)            # 14x14
        self.enc3 = DownBlock(D, D)            # 7x7

        # Bottleneck
        self.flatten = Flatten()               # 7x7 -> 1x1
        self.mid = ConvBlock(D, D)             # stays 1x1
        self.unflatten = Unflatten(D)          # 1x1 -> 7x7

        # Decoder with skip connections
        self.dec3 = UpBlock(D * 2, D)          # 7x7 -> 14x14
        self.dec2 = UpBlock(D * 2, D)          # 14x14 -> 28x28
        self.out_conv = nn.Conv2d(D * 2, in_channels, kernel_size=3, stride=1, padding=1)

        # Time embedding MLP: t ∈ ℝ → ℝ^D
        self.time_mlp = FCBlock(1, D)
        # ===== end of code ====

    def forward(
        self,
        x: torch.Tensor,
        t: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            x: (N, C, H, W) input tensor.
            t: (N,) normalized time tensor.

        Returns:
            (N, C, H, W) output tensor.
        """
        assert x.shape[-2:] == (28, 28), "Expect input shape to be (28, 28)."
        # ===== your code here! ====
        N = x.shape[0]

        # Encoder
        x1 = self.enc1(x)       # (N, D, 28, 28)
        x2 = self.enc2(x1)      # (N, D, 14, 14)
        x3 = self.enc3(x2)      # (N, D, 7, 7)

        # Bottleneck
        xb = self.flatten(x3)   # (N, D, 1, 1)

        # Time embedding: (N,) -> (N, D, 1, 1)
        t_in = t.view(N, 1)
        t_emb = self.time_mlp(t_in)            # (N, D)
        t_emb = t_emb.view(N, self.num_hiddens, 1, 1)

        xb = xb + t_emb                         # inject time
        xb = self.mid(xb)
        xb = self.unflatten(xb)                 # (N, D, 7, 7)

        # Decoder with skip connections
        d3 = self.dec3(torch.cat([xb, x3], dim=1))  # (N, D, 14, 14)
        d2 = self.dec2(torch.cat([d3, x2], dim=1))  # (N, D, 28, 28)
        out = self.out_conv(torch.cat([d2, x1], dim=1))  # (N, C, 28, 28)
        return out
        # ===== end of code ====
        raise NotImplementedError()

"""## Implementing the Forward and Reverse Process for Time-conditioned Denoising"""

def time_fm_forward(
    unet: TimeConditionalUNet,
    x_1: torch.Tensor,
    num_ts: int,
) -> torch.Tensor:
    """Algorithm 1

    Args:
        unet: TimeConditionalUNet
        x_1: (N, C, H, W) input tensor.
        num_ts: int, number of timesteps.
    Returns:
        (,) loss.
    """
    unet.train()
    # ===== your code here! ====
    device = x_1.device
    N = x_1.shape[0]

    # Sample starting noise x_0 ~ N(0, I)
    x_0 = torch.randn_like(x_1)

    # Sample t ~ U(0, 1) per sample
    t = torch.rand(N, device=device)

    # Broadcast t to image shape
    t_broadcast = t.view(N, 1, 1, 1)

    # Linear interpolation along path
    x_t = (1.0 - t_broadcast) * x_0 + t_broadcast * x_1

    # Target velocity (constant along the path for linear interpolation)
    v_target = x_1 - x_0

    # Predicted velocity from UNet
    v_pred = unet(x_t, t)

    # MSE loss
    loss = torch.mean((v_pred - v_target) ** 2)
    return loss
    # ===== end of code ====
    raise NotImplementedError()

@torch.inference_mode()
def time_fm_sample(
    unet: TimeConditionalUNet,
    img_wh: tuple[int, int],
    num_ts: int,
    seed: int = 0,
) -> torch.Tensor:
    """Algorithm 2

    Args:
        unet: TimeConditionalUNet
        img_wh: (H, W) output image width and height.
        num_ts: int, number of timesteps.
        seed: int, random seed.

    Returns:
        (N, C, H, W) final sample.
    """
    unet.eval()
    # ===== your code here! ====
    device = next(unet.parameters()).device
    H, W = img_wh

    torch.manual_seed(seed)

    N = 16   # number of samples to generate
    C = 1    # MNIST digits are grayscale

    # Start from Gaussian noise at t = 0
    x = torch.randn(N, C, H, W, device=device)

    dt = 1.0 / num_ts

    for k in range(num_ts):
        t_val = k / num_ts
        t = torch.full((N,), t_val, device=device)
        v = unet(x, t)               # predicted velocity
        x = x + dt * v               # Euler step

    return x.detach().cpu()
    # ===== end of code ====
    raise NotImplementedError()

class TimeConditionalFM(nn.Module):
    def __init__(
        self,
        unet: TimeConditionalUNet,
        num_ts: int = 50,
        img_hw: tuple[int, int] = (28, 28),
    ):
        super().__init__()

        self.unet = unet
        self.num_ts = num_ts
        self.img_hw = img_hw


    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: (N, C, H, W) input tensor.

        Returns:
            (,) diffusion loss.
        """
        return time_fm_forward(
            self.unet, x, self.num_ts
        )


    @torch.inference_mode()
    def sample(
        self,
        img_wh: tuple[int, int],
        seed: int = 0,
    ):
        return time_fm_sample(
            self.unet, img_wh, self.num_ts, seed
        )

"""# Part 2.2: Training the Time-conditioned UNet"""

# Feel free to use code from part 1.2.1
# as they should be very similar
# ===== your code here! ====

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyperparameters
batch_size = 256
learning_rate = 1e-4
hidden_dim = 128
num_epochs = 5
num_ts = 50

# Datasets / loaders (reuse MNIST)
transform = ToTensor()
train_dataset = MNIST(root="./data", train=True, download=True, transform=transform)
test_dataset  = MNIST(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader  = DataLoader(test_dataset,  batch_size=batch_size, shuffle=False)

# Model + FM wrapper + optimizer
time_unet = TimeConditionalUNet(in_channels=1, num_classes=10, num_hiddens=hidden_dim).to(device)
time_fm_model = TimeConditionalFM(time_unet, num_ts=num_ts, img_hw=(28, 28)).to(device)

optimizer = torch.optim.Adam(time_fm_model.parameters(), lr=learning_rate)

# Training loop
tc_train_losses = []
for epoch in range(num_epochs):
    for images, _ in tqdm(train_loader):
        images = images.to(device)

        loss = time_fm_model(images)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        tc_train_losses.append(loss.item())

    print(f"[TimeConditionalFM] Epoch [{epoch+1}/{num_epochs}] - Loss: {loss.item():.6f}")

# Plot training loss
plt.figure(figsize=(6,4))
plt.plot(tc_train_losses)
plt.xlabel("Iteration")
plt.ylabel("Flow Matching Loss")
plt.title("Time-conditional FM training loss")
plt.grid(True)
plt.show()
# ===== end of code ====

"""# Part 2.3: Sampling from the Time-conditioned UNet"""

# Sampling from the UNet
# ===== your code here! ====

samples = time_fm_model.sample(img_wh=(28, 28), seed=0)  # (N,1,28,28)
from torchvision.utils import make_grid

grid = make_grid(samples, nrow=8, padding=2)
media.show_image(grid.permute(1, 2, 0))
# ===== end of code ====

"""# Part 2.4: Implementing a Class-conditioned UNet"""

class ClassConditionalUNet(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        num_hiddens: int,
    ):
        super().__init__()
        # ===== your code here! ====
        self.in_channels = in_channels
        self.num_hiddens = num_hiddens
        self.num_classes = num_classes

        D = num_hiddens

        # Encoder
        self.enc1 = ConvBlock(in_channels, D)   # 28x28
        self.enc2 = DownBlock(D, D)            # 14x14
        self.enc3 = DownBlock(D, D)            # 7x7

        # Bottleneck
        self.flatten = Flatten()
        self.mid = ConvBlock(D, D)
        self.unflatten = Unflatten(D)

        # Decoder with skips
        self.dec3 = UpBlock(D * 2, D)
        self.dec2 = UpBlock(D * 2, D)
        self.out_conv = nn.Conv2d(D * 2, in_channels, kernel_size=3, stride=1, padding=1)

        # Time embedding
        self.time_mlp = FCBlock(1, D)

        # Class embedding
        self.class_emb = nn.Embedding(num_classes, D)
        # ===== end of code ====

    def forward(
        self,
        x: torch.Tensor,
        c: torch.Tensor,
        t: torch.Tensor,
        mask: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """
        Args:
            x: (N, C, H, W) input tensor.
            c: (N,) int64 condition tensor.
            t: (N,) normalized time tensor.
            mask: (N,) mask tensor. If not None, mask out condition when mask == 0.

        Returns:
            (N, C, H, W) output tensor.
        """
        assert x.shape[-2:] == (28, 28), "Expect input shape to be (28, 28)."
        # ===== your code here! ====
        N = x.shape[0]

        # Encoder
        x1 = self.enc1(x)
        x2 = self.enc2(x1)
        x3 = self.enc3(x2)

        # Bottleneck: flatten
        xb = self.flatten(x3)   # (N, D, 1, 1)

        # Time embedding
        t_in = t.view(N, 1)
        t_emb = self.time_mlp(t_in)   # (N, D)

        # Class embedding
        c_emb = self.class_emb(c)     # (N, D)

        if mask is not None:
            # mask: 1 -> keep class, 0 -> drop class (unconditional)
            mask_ = mask.view(N, 1)
            c_emb = c_emb * mask_

        total_emb = t_emb + c_emb      # (N, D)
        total_emb = total_emb.view(N, self.num_hiddens, 1, 1)

        xb = xb + total_emb
        xb = self.mid(xb)
        xb = self.unflatten(xb)

        # Decoder with skips
        d3 = self.dec3(torch.cat([xb, x3], dim=1))
        d2 = self.dec2(torch.cat([d3, x2], dim=1))
        out = self.out_conv(torch.cat([d2, x1], dim=1))
        return out
        # ===== end of code ====
        raise NotImplementedError()

def class_fm_forward(
    unet: ClassConditionalUNet,
    x_1: torch.Tensor,
    c: torch.Tensor,
    p_uncond: float,
    num_ts: int,
) -> torch.Tensor:
    """Algorithm 3

    Args:
        unet: ClassConditionalUNet
        x_1: (N, C, H, W) input tensor.
        c: (N,) int64 condition tensor.
        p_uncond: float, probability of unconditioning the condition.
        num_ts: int, number of timesteps.

    Returns:
        (,) loss.
    """
    unet.train()
    # ===== your code here! ====
    device = x_1.device
    N = x_1.shape[0]

    # Noise endpoint x_0 ~ N(0, I)
    x_0 = torch.randn_like(x_1)

    # Sample t ~ U(0,1)
    t = torch.rand(N, device=device)
    t_broadcast = t.view(N, 1, 1, 1)

    # Path
    x_t = (1.0 - t_broadcast) * x_0 + t_broadcast * x_1

    # Target velocity
    v_target = x_1 - x_0

    # Bernoulli mask for unconditioning (0 = uncond, 1 = cond)
    mask = (torch.rand(N, device=device) > p_uncond).float()

    # Predicted velocity
    v_pred = unet(x_t, c, t, mask=mask)

    loss = torch.mean((v_pred - v_target) ** 2)
    return loss
    # ===== end of code ====
    raise NotImplementedError()

@torch.inference_mode()
def class_fm_sample(
    unet: ClassConditionalUNet,
    c: torch.Tensor,
    img_wh: tuple[int, int],
    num_ts: int,
    guidance_scale: float = 5.0,
    seed: int = 0,
) -> torch.Tensor:
    """Algorithm 4

    Args:
        unet: ClassConditionalUNet
        c: (N,) int64 condition tensor. Only for class-conditional
        img_wh: (H, W) output image width and height.
        num_ts: int, number of timesteps.
        guidance_scale: float, CFG scale.
        seed: int, random seed.

    Returns:
        (N, C, H, W) final sample.
        (N, T_animation, C, H, W) caches.
    """
    unet.eval()
    # ===== your code here! ====
    device = next(unet.parameters()).device
    H, W = img_wh
    N = c.shape[0]
    C = 1

    torch.manual_seed(seed)

    # Start from noise at t=0
    x = torch.randn(N, C, H, W, device=device)
    dt = 1.0 / num_ts

    caches = []

    for k in range(num_ts):
        t_val = k / num_ts
        t = torch.full((N,), t_val, device=device)

        # Unconditional (mask = 0)
        mask_uncond = torch.zeros(N, device=device)
        v_uncond = unet(x, c, t, mask=mask_uncond)

        # Conditional (mask = 1)
        mask_cond = torch.ones(N, device=device)
        v_cond = unet(x, c, t, mask=mask_cond)

        # CFG
        v = v_uncond + guidance_scale * (v_cond - v_uncond)

        # Euler integration
        x = x + dt * v

        caches.append(x.detach().cpu())

    final = x.detach().cpu()                            # (N, C, H, W)
    caches = torch.stack(caches, dim=1)                # (T, N, C, H, W)
    caches = caches.permute(1, 0, 2, 3, 4)             # (N, T, C, H, W)
    return final, caches
    # ===== end of code ====
    raise NotImplementedError()

class ClassConditionalFM(nn.Module):
    def __init__(
        self,
        unet: ClassConditionalUNet,
        num_ts: int = 300,
        p_uncond: float = 0.1,
    ):
        super().__init__()
        self.unet = unet
        self.num_ts = num_ts
        self.p_uncond = p_uncond

    def forward(self, x: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: (N, C, H, W) input tensor.
            c: (N,) int64 condition tensor.

        Returns:
            (,) loss.
        """
        return class_fm_forward(
            self.unet, x, c, self.p_uncond, self.num_ts
        )

    @torch.inference_mode()
    def sample(
        self,
        c: torch.Tensor,
        img_wh: tuple[int, int],
        guidance_scale: float = 5.0,
        seed: int = 0,
    ):
        return class_fm_sample(
            self.unet, c, img_wh, self.num_ts, guidance_scale, seed
        )

"""# Part 2.5 Training the Class-conditioned UNet"""

# Feel free to use code from part 1.2.1
# as they should be very similar
# ===== your code here! ====

cc_hidden_dim = 128
cc_num_ts = 300
p_uncond = 0.1
cc_num_epochs = 5
cc_lr = 1e-4

cc_unet = ClassConditionalUNet(
    in_channels=1,
    num_classes=10,
    num_hiddens=cc_hidden_dim,
).to(device)

cc_fm_model = ClassConditionalFM(
    unet=cc_unet,
    num_ts=cc_num_ts,
    p_uncond=p_uncond,
).to(device)

cc_optimizer = torch.optim.Adam(cc_fm_model.parameters(), lr=cc_lr)

cc_train_losses = []
for epoch in range(cc_num_epochs):
    for images, labels in tqdm(train_loader):
        images = images.to(device)
        labels = labels.to(device)

        loss = cc_fm_model(images, labels)

        cc_optimizer.zero_grad()
        loss.backward()
        cc_optimizer.step()

        cc_train_losses.append(loss.item())

    print(f"[ClassConditionalFM] Epoch [{epoch+1}/{cc_num_epochs}] - Loss: {loss.item():.6f}")

plt.figure(figsize=(6,4))
plt.plot(cc_train_losses)
plt.xlabel("Iteration")
plt.ylabel("Class-conditional FM Loss")
plt.title("Class-conditional FM training loss")
plt.grid(True)
plt.show()
# ===== end of code ====

"""# Part 2.6: Sampling from the Class-conditioned UNet"""

# Sampling from the UNet
# ===== your code here! ====

# Example: generate one sample per digit 0–9
digits = torch.arange(0, 10, device=device, dtype=torch.long)

samples, caches = cc_fm_model.sample(
    c=digits,
    img_wh=(28, 28),
    guidance_scale=5.0,
    seed=0,
)

from torchvision.utils import make_grid
grid = make_grid(samples, nrow=10, padding=2)
media.show_image(grid.permute(1, 2, 0))
# ===== end of code ====

